# This rule is not used by the project sleepod-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the sleepod.sleepod.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sleepod-controller
    app.kubernetes.io/managed-by: kustomize
  name: sleeppolicy-editor-role
rules:
- apiGroups:
  - sleepod.sleepod.io
  resources:
  - sleeppolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sleepod.sleepod.io
  resources:
  - sleeppolicies/status
  verbs:
  - get
