apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deployment
  name: test-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
---
apiVersion: sleepod.sleepod.io/v1alpha1
kind: SleepOrder
metadata:
  name: sleeporder-test-deployment
  namespace: default
spec:
  targetRef:
    kind: Deployment
    name: test-deployment
  wakeAt: "08:00"
  sleepAt: "09:00"
  timezone: "UTC"