apiVersion: sleepod.sleepod.io/v1alpha1
kind: SleepPolicy
metadata:
  labels:
    app.kubernetes.io/name: sleepod-controller
    app.kubernetes.io/managed-by: kustomize
  name: sleeppolicy-sample
spec:
  # TODO(user): Add fields here
